#! /bin/sh
killall sxhkd

sxhkd &

bspc monitor -d term web emacs mail media foo

bspc config border_width         2
bspc config window_gap           10
bspc config normal_border_color '#1d1f21'
bspc config focused_border_color '#1d1f21'
bspc config active_border_color '#1d1f21'


bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config paddingless_monocle  false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Surf desktop='^2' state=fullscreen
bspc rule -a mpv desktop='^5' state=fullscreen
bspc rule -a Emacs desktop='^3' state=tiled

/home/stephen/.config/bspwm/pepperbar.sh &
#killall mypanel; /home/stephen/.config/bspwm/mypanel &
