#! /bin/sh
killall sxhkd

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Surf desktop='^2' state=fullscreen
bspc rule -a mpv desktop='^5' state=fullscree

./mypanel | lemonbar  -g x20 -B "#222222" -F "#cccccc" -f "$PANEL_FONT" &
