#! /bin/sh
killall sxhkd
killall lemonbar
killall mypanel

#-------------------------------------------------------------------------------

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           20

bspc config split_ratio          0.58
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle  false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Surf desktop='^2' state=tiled
bspc rule -a mpv desktop='^5' state=fullscreen

~/.config/bspwm/mypanel &

