#!/bin/sh
PANEL_FONT="-*-fixed-*-*-*-*-10-*-*-*-*-*-*-*"
export PANEL_FONT

#"-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1"
PANEL_FIFO=/tmp/panelfifo

battery() {
	echo "test bat"
}


[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"
function panel_bar {
	buf=""
	buf="${buf} $(battery)"
}

panel_bar | lemonbar  -g x20 -B "#222222" -F "#cccccc" -f "$PANEL_FONT" &
