#!/bin/sh

PANEL_FONT="-*-monospace-*-*-*-*-14-*-*-*-*-*-*-*"

#PANEL_FONT="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1"
PANEL_FIFO=/tmp/panelfifo

export PANEL_FONT 
battery() {
  printf "BAT Stats"
}


[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

#clock() {
#  while true; do
#    DATE=$(date "+%T %a, %B %e %Y")
#    printf "$DATE"
 #   echo "$DATE" > "$PANEL_FIFO" 
#    sleep 5
#  done
#}
while true; do
    NOWDATE=$(date "+%T %a, %B %e %Y")
    echo -e "D $NOWDATE"
    sleep 1 
done > "$PANEL_FIFO" &

while true; do
  BAT=$(acpi | grep 'Battery 0' | awk ' {print $4} ' | sed 's/.$//')
  #BAT1=$(acpi | grep 'Battery 1' | awk ' {print $4} ' | sed 's/.$//')
  echo -e "B$BAT"
  sleep 10
done > "$PANEL_FIFO" &

while true; do
  VOL=$(amixer |grep 'Left: Playback' | awk ' {print $5} ' | sed 's/^.//;s/.$//')
  echo -e "V$VOL"
  sleep 30
done > "$PANEL_FIFO" &

while true; do
  wifi_ap=$(iwconfig 2>&1 |grep ESSID | awk ' {print $4} ' | sed 's/ESSID:"//;s/.$//')
  wifi_qual=$(iwconfig 2>&1 |grep 'Link Quality' | awk ' {print $4} ' | sed 's/level=//;s/\/..//') 
  echo -e "W$wifi_ap - $wifi_qual dBm"
  sleep 10
done >  "$PANEL_FIFO" &

#bspc subscribe report > "$PANEL_FIFO" &

#while true; do
#  printf "$(clock)"
#  sleep 1
#done

#buf='S'
#buf="${buf} $(battery) $(clock)"

#echo "$buf" > "$PANEL_FIFO" &
#clock &

#~/.config/bspwm/panel_bar < "$PANEL_FIFO" | lemonbar  -g x25 -B "#222222" -F "#cccccc" -f "$PANEL_FONT" | sh &
~/.config/bspwm/panel_bar < "$PANEL_FIFO" | lemonbar  -g x25 -B "#222222" -F "#cccccc" -f "$PANEL_FONT" | sh &

