#!/bin/sh

while read -r line ; do
  case $line in
    D*)
      clock="${line#?}"
      ;;
    B*)
      bat0="${line#?}"
      ;;
    B*)
      bat1="${line#?}"
      ;;
    V*)
      vol="${line#?}"
      ;;
    W*)
      wifi="${line#?}"
      ;;
  esac
  printf "%s\n" "%{r}AP: ${wifi} | vol: ${vol} | bat: ${bat} | ${clock}"

done

