#!/bin/sh

while read -r line ; do
  case $line in
    D*)
      clock="${line#?}"
      ;;
    B*)
      bat="${line#?}"
      ;;
    V*)
      vol="${line#?}"
      ;;
  esac
  printf "%s\n" "%{r}vol: ${vol} | bat: ${bat} | ${clock}"

done

